services:
  trader:
    build: .
    secrets:
      - db_name
      - db_password
      - db_user
      - app_env
    environment:
      APP_ENV_FILE: /run/secrets/app_env
      DB_NAME_FILE: /run/secrets/db_name
      DB_PASSWORD_FILE: /run/secrets/db_password
      DB_USER_FILE: /run/secrets/db_user
      RUNTIME_ENVIRONMENT: DEV
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16.4
    secrets:
      - db_password
      - db_name
      - db_user
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB_FILE: /run/secrets/db_name
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
secrets:
  app_env:
    file: ./.app.env
  db_password:
    file: ./.db.password
  db_name:
    file: ./.db.name
  db_user: 
    file: ./.db.user
volumes:
  db-data: