FROM golang:alpine3.20 AS build

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download 

COPY . ./

RUN go build -o /traderbot

FROM alpine:3.20 AS final

ARG USER=user

RUN adduser -D $USER \
        && mkdir -p /etc/sudoers.d \
        && echo "$USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$USER \
        && chmod 0440 /etc/sudoers.d/$USER

USER $USER

WORKDIR /

COPY --from=build /traderbot /traderbot

ENTRYPOINT ["/traderbot"]

